apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    GATEWAY: ENC[AES256_GCM,data:toIfmpjGYq/Hktz1bA==,iv:C2QNFQu1VIpexwdi75Z7MoFgGr/Y+lqfX6bJjBfnar4=,tag:c2vm2BWVpN/JUAJ/aTF1vw==,type:str]
    VIP: ENC[AES256_GCM,data:Vqkzmw5JtA+YAQt8OVzS,iv:78zlL/DtiIPhtPmYIkOnOfeMK2ttGVxUrZ/O17An2L8=,tag:9rMTxVS2j48u3RL8Ln3Ouw==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:LO86LUlsYiZI9X+saBoN,iv:7De13WpVM8P4g84s4KaQbGGj8e595T3UEu9nqfuNqeg=,tag:A7m0DZ4WaU/G6EOIeVJ9vg==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:vpH7zamddRsXkCdK9CtRxtOKOSwz5vkq5KDFK+8zhw==,iv:1DtpU4bAjk5G57HVcjHJ2UfkOsF/hlB3ZM4dzwvX/mo=,tag:zjMW7pBsqfWLwp13+9jg9A==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:/rzYl51rAzBhT1i2Cn/H,iv:QYGbvb91u9SMZjjsaGJ59NzDyr5s1GBmlMYGRhHTGr8=,tag:BJWJ2TVcn+lm5U6sPVG/Rw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:AaBEvMXdiMCtQKhcGJho,iv:50dLRSV3VnKT0qTYNkBqf94XTKR1FMPwpfdAnFGTYPE=,tag:4XR54XUvayH/hbPIM3KrwQ==,type:str]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:+AZVLtQYLd/fIDwnd+eE,iv:GS852FBZWEN1l7a08UEFtdoHLUKFSevt03JBnNrTt4c=,tag:ZhWBJtu+7sS0mhQcX/7ubw==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:9CRXCTjDfCjUSp61fK+y,iv:1+14eg0O2e/jkkKHfLqnDXkuLEB1jwJSyTKQSH76j0o=,tag:HfZ6rFEvcmgMbAV+rmtg1A==,type:str]
    DOMAIN_0: ENC[AES256_GCM,data:CJLzzeWNGJYl,iv:u1ejZw5NYxHmiEPSCFkYyUYXxenhMuLNGKjDW8YbHt0=,tag:rmip8zn+SbLNv3JSak0J2w==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:f0fFQf0BCODMeC2LGtxY2w==,iv:AGhHdTvSSC5rXkf2yJdhHtMsC91y8U2ouxsNn9JNvC8=,tag:0GHSd62btMD5MlE4b5w8Xg==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:C3C+eNVNq0jZZamgGKLhapCvO7Psi1yeVn3XBkD81BSL0TO7ErDK1g==,iv:umskdJtDIVG+9kJUTUhqK11H8IUQcGf+3Aa8M/zKEcE=,tag:r0zziKIdzF9UDTmeaxFssA==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:YX7IQPmYLFrJug1wMulqH6nTr6EXs6js9IfYkvZGrsyl2nFX/2LIsPaOKYLKUePjZsOnkic37TY=,iv:M6zPdzS0e+kbKrM5sMj5PUiQJOzATG+3Ui6w4Yipez0=,tag:Fy8UhYbrrDzzOH8CVuNWIA==,type:str]
    PODNET: ENC[AES256_GCM,data:b8ySydHTKz0qdqr7YA==,iv:M5WSMBw+GVhDQh+zcUurDL++2IJQjKuCncightBGyu0=,tag:dNNtHH9epoefvoZ9T0znIQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:Qeu7t0vVhrlCvrOMpw==,iv:5GWZCcYRzDZ0nxk+nymxI+EWcB8AGFfjQfUGWGqYqaQ=,tag:EykrjBVJX1V2MbuNjvEelw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:aKDzhA==,iv:bL3Y38PuY6Fiel6GDyS4AeL4J4YS/tzXgSvlLx7Oebc=,tag:C2UL1xzVci2acAdkMBwB7A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1vrkd2lkaazv7spv24r3lmxasuhew82yda7klaxt6cenfl7ce2y6qaxe8y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aXRFRUQ1KytKTmJxRmJj
            NjF6NnNBdEJpSTg0UTBlc1BzNDN6NmJTazJvCjdyUW9yUGZ0enUva2FKQkZyVW1k
            VElhQng0Z2s1QXI4cFRPU09YRHpnOHcKLS0tIHJyM3J6eTh6Y3RXNE9UbVRVdUpz
            UDI4cHBzTEswL2VXbVlZc2VFSmtyZzgKoIWgqnbwIGYDVuY9bqhbBuGo+Cfe2OWp
            iXj7C37QNp6Cl/V0uXusth8lNfE/4aB2Ka+HUEUNt03pFU47TJTEkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T03:25:06Z"
    mac: ENC[AES256_GCM,data:fliQGmgcU/vgLkb6mPUgHbXNcxgAFFeE1Zd6Ve8DbY3pfIgkxvAXDB+GU80tMEVO4BCEquP6QHx9pjrXRiV9xk1T9pDpgpewBRabDMIlAZegGR7n21G8Q8rJkW2NI1M8q2WW/g3RlJqHLK8m/bKaELVljQwYHvtd8j9xuYfFv1o=,iv:mzGKkK9MDj1G4Uvqx5S+a4ItzhZhy4dUmRgkzOTjVUo=,tag:M+LpYX/lPgt5fvrSYrbHPA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
