apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    GATEWAY: ENC[AES256_GCM,data:pTjOOoHtOwweQysxAg==,iv:KIyuYSHImezPhlV7ZEO884w0Ornqre/0d3G0A8aIyvo=,tag:aFEeAJ7hAU28yYWtFSkDKQ==,type:str]
    VIP: ENC[AES256_GCM,data:BiPwW2e0qJqgk+GR4xKc,iv:314RUuLbUx70wOTVDAc5SneHc0iEZe8qy+ItI/+9Bfg=,tag:gCZggJMH7LLr4u5rA1iyOA==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:WZGzpnJ6Y9I1J+RDHUib,iv:NfehY/Neu2SGUnbRpVKJm4Sych5syvkrcHcjBi1Rlug=,tag:Z1wc+lpztuAVDwSnRSIZ+Q==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:KMjMdxotETlMYI0SqHD+NFEo0v3Dm/7FNmPRc2chWg==,iv:XYNd1OdgrKo7Irm5R6553iY4ueNnjBagAMjZcs+XBUY=,tag:Cl/VOO6YMiun8JNcwr054Q==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:PoiKqpwHgSrK1HWcakPS,iv:SjX5PxYqXKTvcMY9N9TrSux/pK7JSIG2+gLQgwiov6A=,tag:VfdFZwPLOkuCuMYagX0GEg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:J18+VPjWxnJZca2UiFNi,iv:tRLtYbsH1qp9uT+HaUDzMCM8E6gZUriaDZweLWN+KwY=,tag:HBXUw1Iw9eZ9u4Jy/z6JNw==,type:str]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:/AeMy+eFIqjzLHjLj7pB,iv:vL18ef1+qX4vwA+YXY742dNMrUaLclpHB2XSDG9oGgw=,tag:KMKf72sfhgD8fKj/Q213rw==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:51+0zRj1vFh4MsFdK0mB,iv:mrhTU46Iokmzerkcp+yqtPTpN2V0n++2nKxefhzuMS4=,tag:6iuEbUZQH7OuJMyTjoqr6w==,type:str]
    DOMAIN_0: ENC[AES256_GCM,data:6/d3JyAsmJ+Y,iv:dXBQtgzea1AAiQo0UfQ9LUEqCMS31ziin5ubU7LFryo=,tag:3YsnlDBQYCslYgFg8l6huw==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:CsN8W3qIbukn5COLkcUx1w==,iv:o4RUU0Ji/Z1pQ7FP9PTaGNPaZ2qoZ4L8hOxC0vwDO0o=,tag:12Qy3WZpQnYCSMOiS6ZzcA==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:lU8YiZ9GVNnnWVmL1Y65ln+khoRyKHLPi6YQ5U5xC+2fXVcFrURFLA==,iv:F+cQ0wzpNna4kkvoE9ggNNcbyhQsuvAg6PlA9NqGi38=,tag:W2iWF+Iife4qHBSu6IQADg==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:ZUjthw9IKxoxbgtxpDwCN4ZVIBbHosYegN6D+SDMfeueucXLbUSsqDBwrEycTzY0TmPPnU4AQkk=,iv:09yGzhtQ7ARlwNjTkE/jDp9fGmylHHTYBYynNe6kTTk=,tag:ow+W9InnP7lDHqmpFqmq8A==,type:str]
    PODNET: ENC[AES256_GCM,data:qgnDuEwyMWy2e1D+Cw==,iv:4PTfe9YxxTP+e79C6rvxEezmdqVx3iWvScnw8TN/MhI=,tag:ooPMN0cXthWrI9SAj6gx1Q==,type:str]
    SVCNET: ENC[AES256_GCM,data:Cfb89PqBxOj0RXaUgw==,iv:8+lOcQwWkMVYAxon4TND2r8MFOMaqHn4qnRQSa+/dCw=,tag:ty87gqa8ix3iEyYUfj6gWQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:SW/eXQ==,iv:aYucgvo5Jhj2a6z0plLgogmGAzUZfLYOzJequKREzWw=,tag:FCVBR/gt0grHPvSsHGg1nA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1vrkd2lkaazv7spv24r3lmxasuhew82yda7klaxt6cenfl7ce2y6qaxe8y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2c25lSWt2VzJ4TjJuRGdx
            Q0orSGxkamNmWE9xMkNmUHhBRlpWZVJydWxNCnk0dm5CRUZ6a1ltampJQjlsM3NB
            ZW5pbm9HeXpJQ0FrRDdIY1h0cmNRRGcKLS0tIElBL2V4a2FaelZMTElFREhMamtE
            MkVUQlVURFhiT1I5WFQveWEzN1dRT00K7DB3hEU7BUhCgwXo7LWUIptqu7Ybn6Q2
            +2qfnw5OA6Vazgxr/E7A/lAalg6zcIsLoC75rHoWOdNxnrX0Arkuww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T04:09:53Z"
    mac: ENC[AES256_GCM,data:ULIa0rpUjo5B+I4B8hv/LKF5JOlusvsVuQFZYmmx2BCl2JGL45zUDclNeYrqOGFgaRwS2ybZHeo7YQ6dkuehrdqzAGAmeDHAbzeyNjyIMgxnv5YRVjmEcd/UEGWd8gJ7Ofqqx3zxx/lk5XEdQpqWQy9cxeCaecvZpipevi1UsSM=,iv:h8dz/ggkgb91Og1/JTzN1MK+/fO7saiS1pfRIK54st4=,tag:ErITay+6bRaxZr51JnF44g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
