apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    GATEWAY: ENC[AES256_GCM,data:gwKxw60lmu/Pw4SvGA==,iv:upZC6/XEE7dy/5z9tFWSVaVWpAw6n8JvR9xDb9xQivE=,tag:Pfhr8eTXkLztG8VDKx2Omw==,type:str]
    VIP: ENC[AES256_GCM,data:I4hsiyQ2fSwG3jDnA65f,iv:UYyACby1bvZKvvnFgJVJ5r+xbJylQBSY7AFcND+AQow=,tag:KWYI05nC0uEGt6Ox1fDuwg==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:8RUCh3rKuWohNdVcqkaL,iv:PkjSKNMHzayiBRS3pzKOz2al9Zz7rDEtjAbPv8WTceU=,tag:+GR9GzemOzFfFfGOzY1/BA==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:CO2U4SVuq6Yw5KK5o+dN3a/3yccl3ervcsgy5i/LuQ==,iv:s5BzxTUPiNWilsipZ/ti6Tpkopvyymo+Py6NmvEfa90=,tag:Na5/Pl9N2Fi1kUmh4XT25A==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:ltz07R/t23FoffXZGU62,iv:VWN5zngqj/pxLrFzDgRDtubE5eSGt4X6IYAk99peeSI=,tag:S/jd34zCpHM5qTJv2/I9BQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:8/b+xdB2MlqgvRpxBksH,iv:1QAGPdxosYOnB0jib20uASiDI0xFYrwRgLw+gfUQi5A=,tag:K8oMxo0PpWviRGOC6EBo/w==,type:str]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:dPb3cqS0Vxacc4KmFFSY,iv:BD9ZIIty0F95EnI1XA6UqNvZDtub947MUTVXLUloxjU=,tag:02l4N5gq2aZ3QcbaBRqZEg==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:gzePleg8sCcEQRL8DO/I,iv:sS+UC5tR9nz7uj6i0lHnbZuL5SHeaXZbGmTQETSLBj8=,tag:2SoIYhbPPY2RNeCrocuUYw==,type:str]
    DOMAIN_0: ENC[AES256_GCM,data:kdAChlACM4uE,iv:mw6noMQ9CRePjYqTG7UzcPjtnkqEQ0ifpRUaTR5x8YM=,tag:S8jDhqR/MlEyYbWJ334VSg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:WWhn0Gtl7hUgskumvPG5wA==,iv:7LVi3IJms75aHLy96eZG7bcrsHPXOtkuwQ0suJNY3wY=,tag:QmnG8gSe2m8HUVMfiQ7kFw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:XVutN7rP6CFJblvMApImBKyOnFKelaqI/agTwPqUjt+RRY4/tJuc1A==,iv:xFcQD0V+OwC6onSCi5B5mxZhII1P6YRHpnXuqVxEQzs=,tag:PtZLOEDlnoroq/+oLybEHw==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:0x5fVwosTE6LItk9QTVOjjDPTlbERFGXhjKbXxXxk4WTtYLIchGC7XX3IZm/HOiqlLP6nR76bFw=,iv:/vyvWwWMGyGPMPyJApkQNyFVhQ0XNxEGEk0i07h7HFY=,tag:WxIPYEIAGIdvU/qKcpDl3Q==,type:str]
    PODNET: ENC[AES256_GCM,data:LiEjNru+Pn5eqV+7Xw==,iv:YptKc6p1j3SYDcXCld4Lg6XLRxe6AvBbl5gRKvbsyL8=,tag:eYiSzVsAET/yoVWrlG6gJQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:PwHI7qtPOGjgLiTRag==,iv:puiCh/LRoq1AZxzdBOAfnfVvN9X9G1eCzuxw4osyFho=,tag:gSChnSLLBI2W3Dm8uuWSiw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:NIbdLQ==,iv:qweO2UgpYnNSnK7MNaZEylEY2bVLJP7lNIlgIveaYsA=,tag:J4rEs35k8p1ncg8Yg7akpw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1vrkd2lkaazv7spv24r3lmxasuhew82yda7klaxt6cenfl7ce2y6qaxe8y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUmwzWlFUQWx2ZWxKcUw2
            QVVhTTdha0lTQ0RXWktEZCtJZFRpdkt3dm0wCnhxZ1o0MTZGVTF3NS9lRUVrdG56
            Mzd2Q3JHNWRpVWRNaU1WOCtrMjA5QkEKLS0tIEFRK1lrOElNQnQ2UVdHZU8rRVZL
            N0dTa0d6ekE1UGpFWkJHZi94M1dJeVUKni+FU/5Jp2aGWjd8rynDbaKg9p67Ypsy
            sp8slQn24rUGW6OUSlgHhAX89x/1SEreSRe0uxoAikslR1WJr+J0aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-25T22:32:08Z"
    mac: ENC[AES256_GCM,data:y6UlHY2mNBSe8DA32tLRriexxjsvcP8Jw3pOKXLYtGvEUzXom601TdHDBaMnL7swE2c64rL10kNOsI9NUzoijQVdyt9vLmmAtbhDvVUx+/PhUpuDrbdth0MxMYBmKMi+j4E+rOkCf5Hk3GSb8MRcJvyz+2waqMwTZ8kfjm1WVzM=,iv:wVEsjtxbKYc+LExTU6h+/0NWGG8mk9v7xTdiuRHUd5Y=,tag:Ga96CxvR6VfuF7lCc5gu+Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
