apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    GATEWAY: ENC[AES256_GCM,data:CL0TPW/iKSDUoLOyUA==,iv:yZCKtFQTvy//0i8f8SSrRny/PArt1fS27XptjwDFk54=,tag:yJxHQ0fcBcdoNL49pqeqlA==,type:str]
    VIP: ENC[AES256_GCM,data:Os/pi3WwqiLIAQS9KR1D,iv:Xhlp9f50n2FFj4/xyTAUpv6acjRB8FCNkUYfa4Olaqg=,tag:CMj7/nkk5RlUdoZDw+C90w==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:bUHwlLS2H/sq3VDzfWGa,iv:Diy/7Ra9oQ3GemgeWifY6Bda0cRUBvHDl9ciOvn7hRA=,tag:Zxkoe2bC8GkwRSMjqIzgtw==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:2ppMF4w7eM02RocWVGnRWBcTuJOKMuh6u1mOGLiyPw==,iv:oNf4cShtF6Yp2bW3e9kATtevJVXq87iiYt3Sxdb+B/U=,tag:oc5jMKp0Ha20nH+INXNLyA==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:HWZN6HET2Z5FAH5Mk9Dv,iv:djS6UkoeffKd6TLqGMUKF8ToWEOlN3gZTMmM9Vp4cAc=,tag:PmoyqdZ5I7W/Q6q+kN1Hdg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:fzSvIc2WDUOYdmZJzQt6,iv:40zEMel0or5OIqU+2z072FS6EGtOuOvhA/IQqS/m47U=,tag:jwA+kplHBzluS+YNeGJmoA==,type:str]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:d/MEHRKj/GIYAzWN2mrD,iv:jes+ITQlDFun2pLrS2+Ai3H/6atXy4aUlooiHR+0WOE=,tag:n33aqEH8BSIeoCs79xKy5w==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:N5ApUUSqoLhWgls2QysQ,iv:OW1PMP2WlxNaK0omLit6B6qI4mTqeGfxl+pcYlE6myo=,tag:LBXDaJCywGVShDdQdgADiQ==,type:str]
    DOMAIN_0: ENC[AES256_GCM,data:qXtSIgSxU0+n,iv:nmg8t99JCaMc+++O3/d8WTjBuYjFjC2T/pPMYrd2lcg=,tag:TnFiStKLGv9vtefhCXQA6A==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:bVW4DJCj8EMF5LjrJQfiPw==,iv:8ZB3KGWhXkfGMADJHcvs1mvvHvJg0qoWgBCJz0NRR08=,tag:QPFURzHASvd1MlrDNlQ+kg==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:1nsGZSy8s+loyGV+QBgm1BtncYSomYhAqCoDkKSfByqbJkKaUj7YSQ==,iv:0ihL2saOV9DymnVsI93YqhnWUZNV2LOp+UHejyNo42E=,tag:/X//F6+GfHsofpxux5qYTw==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:+3gCxwMH79lOvFbxMFGITt+jfufeTPTKuxK6wnBfw0CX+tFrJbXraKYIGosWbnfJnmJwJoDj1Io=,iv:BJIUKFbqOEnIgVrLPaRlHLA5UjFjNLoTFNKm9tbJvoc=,tag:F+oT1lGTio302F345keJKA==,type:str]
    PODNET: ENC[AES256_GCM,data:Fpbc79se/3qTGcry8Q==,iv:G0PCcn16m3EtN5b7nctU6pCI8h52WRdwV8JH1CQn/ME=,tag:QkT6qo9Y0u4S92yiiMXS7g==,type:str]
    SVCNET: ENC[AES256_GCM,data:dmxwXXEfM7U/Gi/wJw==,iv:Llnwq94E8AftqJSCpNP1KV6oQqGsTqJC9YhtvkvimnA=,tag:7EZ+uNGXvCaKUY4mtaiebA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:89maZQ==,iv:q6V6jV2Xjp/GJc5cTFuba5Dsm6/HoaRjZotuHblRkkU=,tag:WVKKMIwsOqbHRIQ62hHWfQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1vrkd2lkaazv7spv24r3lmxasuhew82yda7klaxt6cenfl7ce2y6qaxe8y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVWU1QzBySlRmb0Y3NGxI
            WnM2YStMeHE4STdITkNaVTViYndVQk5zNkdRCk53YXZ5WmJJYWJsa2FkNEt6amRl
            SVBCQXpSaXpKeFFXOGJ6K1pGb1JtSU0KLS0tIC9TMFdGNk5WSy9WaFJNd1Z4dmxB
            T0N6TjNsQ0Z4aW1xcWVsaVJZR3kyUkkKuUtEX84FhT64gsogGWfD6q+6ghpCE4Bo
            nqN/+d7NUZggKSzZfj3aZKNL9TB9M3JOqLWepaYt1xdfvwJlyCOHpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-25T23:31:15Z"
    mac: ENC[AES256_GCM,data:z0niSPdEp38kdgZpYTBO5ZBvgixCf2MUiG0kFgVMFbPg2tEW37zKVsaK/OMZR/tGh0ZPIXuOiuBKf9uauN3UtVd3e4QJFToBt8WpaFrQ5cQB70478z6SkdrWjU1Rr5lMGDi6w72/BTQ894LDZI5SK3kc/+6VnIq09mq6hfucaEo=,iv:TwbJ1SP3jzmpk3J8tiu5auYKbtHKjG6XfcR1JsZZEcg=,tag:mXfux4uP7MOSVpi19B6GAA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
