apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    GATEWAY: ENC[AES256_GCM,data:zVbaqFsph5UBoiqGGA==,iv:sDlwFcgg/63rwsbdMijNNyBjL+y1UJPFGAQ0M7cp9JA=,tag:8omC1DUgz34wfY0NAjXmog==,type:str]
    VIP: ENC[AES256_GCM,data:s3r1Rt0AxuSfFUZsrqAW,iv:x7i1qyl7Orgy4rnOKriEUbqm0V93tzFqZXuikVzI74U=,tag:CoOiMw1YY/8ga4cxjTdmSw==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:0IIzi7yE55m8ZbpUW0oV,iv:Q9GrpGtezErALUmNDCJ++YcvsZ7A5rtUKN2W5VJgPLU=,tag:QENCLuOeUPvPrJ8mAsy4kA==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:z3AQAjJA3Ftu/stGQBC0U99azre6NCgjDVbZtqzl6Q==,iv:LShfk0KrkMWQKWmvfCuUjLQpT3JUBrxsxtDGF4uHhqA=,tag:r4Oty+mrtm0YbxJVjfjoXA==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:N6zwPqqCa6nV2NhCoztq,iv:NOiJUWOskchr8c/BrrKjBq9yeiFZXWMnJA0s4z0hwfo=,tag:Wp111O5pal583KMqXG7oZg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:1YLNrHejHdgMj7nnQ5CU,iv:I0rtfvWirKI77KR/IwtD7CV9/oZ4mlzIky3zTCQvytQ=,tag:+pbL9VXmB5PgZ7X/o7cpOA==,type:str]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:FzF5dHGYJF+2w+dvZtjG,iv:HcSlP1SpjozoCT08FYszheeO0SkHFgchH6kviGX/PlA=,tag:7A5NR7PQNQwW6hhQkmZu+w==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:P/OZKYeHAzGE6wz1vV53,iv:FtUqk860FfjiwF8zOllEIOxrqI79+mJ1wPQmNJvUMoU=,tag:5akgnTxVeC/0QMG0W6sSWg==,type:str]
    DOMAIN_0: ENC[AES256_GCM,data:UV2eWOhAlA7X,iv:RoI3ylLqrjaOVvD1nzR6KFWp2YIgKyBH/vRw47Vli5w=,tag:RS/7kRbtNQUAhYjrdva1Ng==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:q/Kwpeu0UuUBcQsNTKuHgA==,iv:axvna+FUIB85MhZOgj7igJY/D2amYmVzY4xcqMbyIns=,tag:/WckO/vEPPFfsIEwImU3kw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:ur0Wpx3rMo9/V1KutACW4q1Ee74l0MFe/DseCJxq7C7pUdJiO4drfQ==,iv:z93Cr74bReZsFWCUzdnujairqEqQnQFnE12V6i+5TfQ=,tag:QrZ9Y+jd7LvMXuFTQeruqQ==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:qkIYEQnYxm8xKS5wiB4pXfU7jRFttWeK/FjiVzKbFL+ohGbap5azBUr3XZhKbMLu9EDq46MGejw=,iv:TXMaee2mxk/toRwtk3gkVbslmhqAj9dXvLwtPcgJaMs=,tag:8CiLp4tJd+75yVHp9I3fOQ==,type:str]
    PODNET: ENC[AES256_GCM,data:KY/9jxJhMSJpwuNPcw==,iv:WD+7Fe3d1rvbs8HXdKoSJdxfnpQpYsOZJgSSdBa48vU=,tag:c4BeiNT81KPIc4skCKUyvA==,type:str]
    SVCNET: ENC[AES256_GCM,data:nvGPehCyxg5tyeMSAQ==,iv:I8gisBtWJ+RGlESkawsi2Sbm/I6gulE1EX7Sf+3GK0E=,tag:N7jMpTVZy2abSiDxeeQ0MQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:r4otSQ==,iv:3985w9n4zSddj8infMrJn3EUp4ydryZEpzIA/7gCyZ4=,tag:w++fR4SdWv1p+JkwmmByiQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1vrkd2lkaazv7spv24r3lmxasuhew82yda7klaxt6cenfl7ce2y6qaxe8y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZmNrRmVkWngvNmRtRlBU
            eHlramRDTXZrWU53MGpkREdNRVBBR0c5aEJNCjBQLzlMWi9QK3dqSHhhWkx4ZUY4
            aE4wRlR2M3lzLzRwSW5jUGlsWW1FZm8KLS0tIEQ4MnF5RlRNZkJrdW8yejFybmZY
            bS93MWxrTEN2Q2FnNmJSdHRFU1ordDgKb4Bwf80ZimJRSlKpLnqM8nalg3JxlgKf
            fHgs6nTE2hZthuhzwH2ldFLokb/mw5BxfZQhUjNHXZoM03FIq1IdhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-25T23:47:56Z"
    mac: ENC[AES256_GCM,data:vVFraF0aH3qDUmpvz8Lj/73ZPDyOi78XVE9wPiYaOvO8gVGQnAPw0On4WMkpiPApEyDR+eTWVkBn7fZAjVzp7abCvw8SqG0hsYMi2p+XwF/o9ezG4yRmpvbfMoldS+p0qbb+Vl0RqlcJUzT1CIuxhePn9yqnBT6FRnvxrEwu8FU=,iv:zaeURDWVHJWy2NfAsjgjIrtgCPU5i3gzJLkgFGYx6V8=,tag:sxFLvvDQPIcNSqHUHNzMaA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
