apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    GATEWAY: ENC[AES256_GCM,data:egZmgUsoNppzWiGCMQ==,iv:hC8ouwCDtZGD2NWjr+7dNBdYrDSU/9Jnmdis9aJiLx0=,tag:7EY7FYUx02DYvc4Hsoc+XA==,type:str]
    VIP: ENC[AES256_GCM,data:bmsTAmHzVMMSTAay7G6j,iv:C08UJ7F7OH1RGKxiXRO4XgAPMRGfMIe9+GMcw6TTZic=,tag:8pl+6Lc8e221Dw4rJHekYw==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:JeroJfIrwzgWimdBeGP+,iv:C0QXlkQ/RkhchQdEgpRP6oPs22SqddxiObujKQxbJjo=,tag:Uok0AxxZ80Kt/GkeBoJMYQ==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:EN67DDks3C5sjrhcIg+BBC1TjrqQxhN/VO6DjrhFZw==,iv:2tbA0xFftWNKr71DY8Ky4M25iUXG1T7T26uxGT32a18=,tag:zZHdLG1mDPd6QDnKgLxoBw==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:fRoYnLX2e6vdhxeBowlr,iv:Whs9rp3ZPpc8V2nhXue0yasvIhHVFIphiUbfsWzBR7s=,tag:qNuO4PXj1J7tgBJk4QfFcw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:N3/XS4BWbcDHkdoBIR9C,iv:IxEw7Gq5UTRir6YEOlpM+FfNk7BuwBDhz0OXbnHHKRo=,tag:4zoeW8ySxi5sFPJ+XWNozw==,type:str]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:To45pf5tBXjx7+lr1M3r,iv:5BjYcM3ogujtp1Hv7tJHBFjVixS3dH3kzhddcBw84KQ=,tag:iu8rjg1hKmxLTybzc7F6iA==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:xmrdQ45Bbe0cWEYudvI1,iv:qcPXpoJqL/T02EPgMifSfOPe6j/XOOhjiRsPQ9WrEYM=,tag:+3hhH7kG6TClZUIFliC7Sw==,type:str]
    DOMAIN_0: ENC[AES256_GCM,data:Wy8YEUi+Z27s,iv:+5d5emmodiTMxJH6QZ5QCYCM1IaTeOwZ8bbUNhBl+hI=,tag:NYcJQyepNNWRKXmkdR+TwA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:cELc3xvImq9vjVwdhufS4g==,iv:2vjO6brxNo/0ze9/r1lVqqtfNez4x7+HMXsEInPX8ag=,tag:KCUoleqWboHFjMMDJnb5EQ==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:p65YvtWOjwOJ8l4DrMgcVJ+2iZ4XNMqaRxC5wUrTj5wNi5Gcu7kkZA==,iv:7vVKeRqdos7Z2p44sZt6ts/lBkCyjFeqUVNzTDEeRFU=,tag:tKstYqjkIGMBFmaw0YFFfA==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:/2ULxn2B2NVQf7O6TSOlfKFZYIM2HLH+HnXYNjAgqmQDHjfGgo7m59FxrRU3cZG8wGlKbMKiXgM=,iv:wiBWMV6cKCR4sXtgnt0WNhEGdkTYtsXCJ+mkmLTbZa0=,tag:a46lbALumJG/f9nXOes5zw==,type:str]
    PODNET: ENC[AES256_GCM,data:NMRBI9cGukxj+glcmQ==,iv:Q/m3uvzcMMpecxUmS2n9lCEzjOSwWQwyHzEIw2yPa7s=,tag:iBdDXQ2wtV4eJ+TnZUBBCA==,type:str]
    SVCNET: ENC[AES256_GCM,data:kt/WqdB1C0vm4e0xgQ==,iv:VxabpuM5oDrA6mwkxWGJ0yVt+limvXe2uVV01bWa1jM=,tag:WsOMgcF3mV+shaIVNtE0LA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:aCRIaw==,iv:qAV1pttJrFUd67kzElTDE9YU1kAxyAhZzi6oipelMeQ=,tag:6CxfAjOCkAz/kRBVv1CZvg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1vrkd2lkaazv7spv24r3lmxasuhew82yda7klaxt6cenfl7ce2y6qaxe8y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaW8yU2FSbEIvTGJxVnRK
            MGZlQUVMVndxTmYwSWdvb0svYjNCRXBSaHl3Cit6bUNsTDBKd21VUkd0dlpNTVQ2
            Qnh1TmFnNEo3VGFiaXcrMlFQVTBIdUUKLS0tIEkrRVZFNkVhbHkrVzZWc2M2TUs3
            MXZpMTlkc1pmaXFjYUI2QUhBU01XVVEK+nGpLqKxYMh8ijsA3hB0F0+Jf9Hvo1qa
            puFmuCtjH+pwGsp7vpBogN9qy8pndNHdwdHBdz6JyxYOgA4LZCY9Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T03:01:43Z"
    mac: ENC[AES256_GCM,data:Be0zMiMxOTlIJg7xSWZfm34ElxdMBzZ09TcqTOPzvkqs6srt5IACgDIxsqvRvwJiyR0484/vSVAQEHRnpM59rURZimOyM3zedDEbDoVWG9IclEqw9rV5lZ0gXIXSiNwXnoOXAhkMvKRyns6NVopjPd1YWS954T0NeRmF4VF3Pog=,iv:8Z6UF1ikRjwJMt+uKLdXjpAjEP9U6R5KKLTm5xWWYS8=,tag:ILoSDAZCAQEPXaBjZdjf4w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
