apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    GATEWAY: ENC[AES256_GCM,data:mf4uO5WRtQG+eWIffg==,iv:U7ubsZyzddCLv+eGnTweBs+SguiTBFEWMCgSdWUVw/4=,tag:31IrJExOrIoXdKiHwPpPMw==,type:str]
    VIP: ENC[AES256_GCM,data:ffxNsUB6dGVB/g1+Eoff,iv:sI6d0BD6zEGG/WjxfSQeEGm5rp7uig7aacytedw1V3U=,tag:6ipSCBmc7lZHvmfVa2w96g==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:FlRk/2hgvHAyemN3Ti+n,iv:zQAkXi3NC3Q6CqOJAyyWlG1zSSVa9j+Sey96VrAjgRI=,tag:FWgLQW8XJ3Dr6EKr5N58QQ==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:VCjtCMJ4HUzryZ0hU4tKCjQZP9ZNnBcNqX65Dsa5oQ==,iv:WujIzfuaLqzLDKBuK1GeA+vQHJ9eSG1GxKBQMh+1ViI=,tag:frTpTmYhg6fpz0dvkMTYdg==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:GzGvy/vxRi0D5oWEiG1Q,iv:u9cBnDfcaryEfGrGBw/Zb7uo2W0F2WLumtQ4WauiCkw=,tag:KHHCTmHl7AysQw/mYf74Wg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:NK4LRilOz+JRCjSbjX5n,iv:AovZc1AdIkBA/UsNzQQBqMikbWP/H6QYf1N9Kr/HWww=,tag:eSYTduNt7dIWKm2+/zSErg==,type:str]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:xRVv6aMoww+9Hve5DBqL,iv:LsRm7y4+L2zrGtzq3wTYfLlF0dHt+zXlxb3Fq9K+tnE=,tag:qUWRbrAXxFplhccVl0rOjw==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:mF2qefKCef3KZWMAopKy,iv:CO1pzSpAPIQ7oQDfnvZPG/2hJvMCVii68gXZnOxVbYo=,tag:L6F2G0Hsa5RaP498zZWbzg==,type:str]
    DOMAIN_0: ENC[AES256_GCM,data:hefSsdxVcAKO,iv:gLViu1/OIURHW12bB1OKZfTyI13BUTN/HefDAXQj8nY=,tag:UUpXt6bT2MjbAgcDf8EnzQ==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:RDjuQ8q0hfFtzL376kJkBg==,iv:39zQayUzcg2/UyPkHB6WhQMiJN9P43SeWrCTYElZtAs=,tag:jkGfMnri6sV7QtaUjJqMSg==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:QXn0v08t1nHIz0RUEjNcZTcd5x+pRLnSRjFlnLTPZa6BgzlW1ZB+wg==,iv:dSbnKw/oIxAGuTtzPJ8l6Qhoao5kiq5Fp7KAsZiWkG4=,tag:22LEcDk3AWw+lpjua6s3WA==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:Z2f6X5Op8rTFL5NnERmrx/MQTEA0n77rm0EjxX4bfnxnWPa5q5LG4m0vhwH4KerNL8FmfIeAJmE=,iv:3jYRP5fSa6YjTYo4gj7kfrV2lCNA1qOOcSbTGaP4I/M=,tag:/u2oaJPENIrhAPUh6MOyMQ==,type:str]
    PODNET: ENC[AES256_GCM,data:6ZA9Ncf9ChfFlRD3gw==,iv:TuyjXxIJOkJGxBGbKE+zir2zSigBSHZeqzkKuXYr390=,tag:tgb2N9dTdZbpH/QuhMsqZQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:y6p72z/Eb4/Lpaufxw==,iv:+x3fXtruvjz44jIeo8Zty1gOYodinvdRzqmatyWmBNc=,tag:X/3IeWDfinl3l1hHlASENg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:dyYn3w==,iv:JDXP6sdmlW1geXR2pPo5qL5RSRcmo1WXj4sCBaic2N4=,tag:z9c3OFbXgDlZuVpdukQs3Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1vrkd2lkaazv7spv24r3lmxasuhew82yda7klaxt6cenfl7ce2y6qaxe8y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdTFWcHRLUXI2c2VrcjI2
            M0FJMjBuVENaWTBnMXZsbFErVW01Q2lyVUFnCjVtbWlqWWE4Q2Z3Rmo0NGlHeXRB
            d2UrZU9yMCt5WVZGQTJQelRiQ2tXREUKLS0tIDNQQWdtYTNCcWlsc2RQenJEOGlm
            RUpBSVJycWVUdSsxNmhETFRQTENtZ0UKXx3uYtUejKK/e7teaCDrsVmz2YRjFbfi
            Gm8W6islBO0/gK7lNXu5jJDiXlgBf3sjb65eEzmPeaRpfJcK8gmJwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T03:16:03Z"
    mac: ENC[AES256_GCM,data:Bq12FMXFl4KRZ/9UrmYDyFHAuhykTm8AzrqMCagYMRhW4IjexnbSxEwp8+4SxpTH8e1FjDp0FReiIGdXH83Lha7AbXMHjYre20e4E2eZ+1w1RCUEUlPRpli9bDgaL19fq+MCBbkYA0ug184qMM94LbIkFGIXaB7iL656s1kXkKw=,iv:nB07ZTX1v39M1oJ9pHldBBNmRwg67Zm6e+nzX+Skh5A=,tag:SAI6N3ugxa6ZywmkJFAEVQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
