apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hEhxjPPgL3Yg6OxTa+580HjbD/oVHDYKVLgcaCNuiX5DCY2cy45XUh3sDmkU7iVJg9LS6ZhUd83FbKGJlFbnXoCS32LhS32SSPEXRF7a2qrmPPUpme+kvrp36ImsJYSgtutK7KKPyhr0kxZ3lJ7wljmrZZcXd7eEDyHKQwVMe3mscEX4Eyct3kXTSLUEUa+QYY0CbUaZ6RE+XdHNURby1Et17CwT19Cv2m2TKIHkqsmlmUA29kDemWFMUvS7dPeDNGLIzmmEd4KF35hvKlE1Ahhy6xG8vKpm4Gh5HhWER4fm0SrJmtk4A3egcx5vJw3SqcjVqJG4d47W2CG2M/4D3B0Fv7+2tHeEEORN9QqgXTzxRFoVxazDu2pJG8RNE5mU,iv:gXK7z661yQ3Xgnvla4m6hgoaH0Lyg+uqrOvanqy89ZI=,tag:B66ecJ3eHVAX+L2Yn3N62g==,type:str]
    identity.pub: ENC[AES256_GCM,data:jJgmfbeCrjlbI2bbRXjonz2EzCtr+mS+/3DR14xf+8onKf1Lf+gpn3mo1uwrHpIkbOnwGba0Lr4uZ3c6b2smn0IXtsuHpADBo7aBE6c3mqGKMBqa6ifsLI4MH1d/iS/iH1+9vCQSVT/cdi+wGduMIqYERd9eY2252dFFxOJKfuJprqAEq6oULAylpmroQmK/5baQ+m6HJOg+YyjpB05yU7feIcl4oUBQBosX7L7zVjyG0xpiYjOCyAgXKJAFgnK6L68Mn3VRXEZOKtv+XA==,iv:/BDkeOnmqXNiinX6R2w0Gm00y8fNhjl2SrTCucuaqkY=,tag:T1H1P8M9FcC3U+sMXgb5Qg==,type:str]
    known_hosts: ENC[AES256_GCM,data:CG4yYzhAtxUUBCeKgNGQJ10rBiAlONnn2wpahtodkJht61fstBmRTHbBmPCA/9STwcY2eFPDK8VelSnDcep/iNxazaTpJVbm8k/gbBGWhjrzOpJuul6ukBMoVz/Kcif3yBNdLsaU8SX02DnmkVqEZKX2ucvnscEASGXCR3UH6nJSGNue6vgmzhBtiQyNUcUA+S0mLZdFMGO0ei4CQnrwFAEcG0cw0fIeKrsH,iv:TV+n2ARA1DO2Uxa1HUriY84m6IveoSfQ++U38q6FAVg=,tag:rTJHlpccLhkgRtTO/AMZTg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1vrkd2lkaazv7spv24r3lmxasuhew82yda7klaxt6cenfl7ce2y6qaxe8y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTVFtYjJNbXNaRkZLemNa
            SlAvcnA0TEF2Vy9BNXlLaENFRUc0RTlBa1hFClc5NTdaMHRqbHd2YzZsTlBWbG1K
            SVQrc21iVTNOeExVVlVkbUVoN2ovbGMKLS0tIHl3L2NWcWVra3orRWZuSGJSc0Nv
            OVBmVEt2S2huZC9na2RkNkhZaU9WUXcK3O34NC5gCgD7B2fmfOAs0zmsUZTUHF2Q
            Wqy3cEamYyOECZaIaSsVbKl9mRMH0xvlszVheKu88/gBjnWBo2vo5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T00:03:23Z"
    mac: ENC[AES256_GCM,data:pBt7qCQWfxg1NWbMRu5GLTonTBTuaDjkz4OkgFCQzzgfLz5qDpqG71dqMhb4AtRqff1DmcnSAlhPSaEE72OvGGpRinmm71Z7DDWifUt7ofP4VnWQoTxWVJZAGejmJAZ9a2oCnWFDCco8foY3lUPeNyuq6WfJflFZAcJtat2kC4w=,iv:OdC2XpBiai0bnEGzpapjfgZ9Qv0hsOb361LFqGPdwxk=,tag:fvgfaOX2HFflEHCZdmHpEQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
