apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:CyrrOzNcjzp/GjNm2562tSZ50NpJNWU4Uj4CNXk7dj297xVtfUyh92EMbvoBD+LQIItFm2NbD4BK3bLK7TGhb+125z3E01uoSmrZ8CCj5SyEcjjlUzw0dcb2PtPLAGy2BRzRYvpq0s784tjAuzthsAGxAW0u35K4Ktgs+nnrNd4DSv3YzYOuuprBC775Gu7NBs5rwhqcj5p/g+85pVTHRYZfoeR8i7ACM6K9NwqmtPAMfvz/gzlbNoImo4YGrYf8eSP82ulmRTScXSbE/eDWKOn4/12sCmK9lzjLC4Cke8Qp0wX1e1aKu3/iSpB0Ank4W0VIJCyMDTqje/OwGlnt7B/mGv0Y5ex0OjHFnwKS6fRIuN1qGAS5cGEiM0FXlQ2G,iv:yt+vgHase8w1BJGylBJ2suH8sePM1exxPLz97iTw4lE=,tag:ASTQuPNjvjfFCUhA+RM8QQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:5nbv+mFTvuC5oiRHmq+2i3NFuPNPxL2jii0zVjcIQg+3bTUwYd98u22ahTU3c/9OrYfnCiJceFTVxbgXpe9W6nPJJmgDrRv3fnwGm9rMdHqlod90Cg3O6b1Nb8ie0BhiTwFyG+oURNpJQo1Lq4f188nbW9tVWROSxrZfJkEVVf+zKFsTvmCLibpj9TQ6HpnShZ63aq/aknHIKKwONTk4I+ci0YmYp2tHtuJDjKZCg2cPLW2MtoG4OzpHPXSTmnRplTth9sqlUO7nOvOR1Q==,iv:bzlOob1pHdxN5F5EMyYm4SPdzBo8XrQhIUU1jjsOqcg=,tag:gexuRqKcFEW8r2or+7RFXg==,type:str]
    known_hosts: ENC[AES256_GCM,data:V3cWkowPlWosBwr0M1ZuWJBekTZDvxBtSWoYd6V55mSEBJ3Gq5k20b+HcGyRH8DyXJfYHsMltMUHW2KOA8qClTzoiWqZRWbTP6x+EB7LHSaq1333S+c3dlZq1gT9S5LuTd2dUqdx4XJhPYG1QkDQzoRnAApqH5akCoX6kirWODeogRBTXYfyJ8XXL8KYmBWX9jiuopPzPaj8zPQ2gh1/XsN9ZfzxCYn8R0y3,iv:uTa8VXaH/DwK5lGNQkdKLqwwLcs08JHjLKNqp4PjNWs=,tag:IABQ0nl1WpYjXQLQeUZa6A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1vrkd2lkaazv7spv24r3lmxasuhew82yda7klaxt6cenfl7ce2y6qaxe8y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTjY0TVBESDFjYithN2FQ
            VlRxY01TT3lER3hWYnR3enVmZWtCem9yMTIwClZXOWhIcXFONENpZkVQb0liQmJo
            Vkp0Q1cyaEdKUmJ5cVFYZmQ0Zlhia3cKLS0tICtUSWtBaDNBZkM3M2RFVno0UGtm
            VXdkcXFnTmZQZjYyMWJMaDl0VFhScXcKUjwFT+E3zP1zsEx4tjUJ2xVndL2HwD6r
            ACgn26gRcukxIFrLT5PTpHp49oPm5K6xm3DnDoNXYAQSYoIpDy8UTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T03:39:39Z"
    mac: ENC[AES256_GCM,data:+TnIkuyw60ACL7Qw+KCAaStjk9rIIRIwpxNJ+59yNpXIX6QFiuIX/4L4NE8+I/+lOoOocfj2umfPtS0QnHUMAPpVijv1OOIkT/GdmGuigM+HL5eXmtZr6egkVstHjcNQw4TBkhrJrvOxNH/LCbccp0D0pcZziQBRohUAPe5JATs=,iv:AJeh1dTYLOWoEzfWsuOwd1FvTK98VbNFCdFL4At8y6g=,tag:xKqQGSWQTNqI1rFJ8svGVg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
