apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1c50E3KKncPMuCcal7uSnutM0BSaJraqcf0FqBhERgHXadIDTyXV7xLxPf4pQj3sqJKpTtGcfeLkUdeBl0eUDCugQ8Mfw9wIiFDNnXZpE49Q6kt/T//IJvo3spt5Y/Nh2oFYza0gaKC1vWHegUKUgOAl84Q97BYz+rAXzxmv3o5e9o/v5wzCnXWonvWQpEAydqV/lWqM1qZxwYy3dsgnx1uyEDlDyo4lm1klsLVWUeAGGa42CiRuMNd2JqSXjayW9L2u65iXkZc9epgSVygEnG39daSPX3sMSGSNY/j7nbGf77R04GGgIcdmHNQj2F5l1tjx/eL2mHhHl9mWm7IipmH7tok2z/A24CsBElUQGHwFUWbuUHIxqdnfAYTIPyXt,iv:3qWBtbppLq05rTUPRqph6ffwyRSUGSo3viHedux/O3E=,tag:jdhoADZSUYMKcNW3ubnAew==,type:str]
    identity.pub: ENC[AES256_GCM,data:dK7VZbFlR32RIP4pHcjxkb4DTGlLrS8JNFyPW+8vWMQsRMC9sPnAiINbA48XPssnj32V8xU++wHKT5FD5tXhLEQgRqcphHBW8Gi3+EcjdFaYWZFfKpNDHPdAkQGhUZaBANuD1WFxj42APDkeSZettewadvVyjoPAs9n3tgOarmyLWc26hhAsesVFExbbzvZEMv45Q8BYzQaHQe8k0o882VQzPcN/ow7EwuwmUq3GVfLrpKDRZZ3hs4Q6Y0Ynzvn5VKKTnGovJU89quvkOw==,iv:sWJ35/1s5GuNf/6ysRjbARaarKabEgVoyiIg6sFYcXs=,tag:1AJBFAFwVEGnkH35eW+j9g==,type:str]
    known_hosts: ENC[AES256_GCM,data:lPc1fF3mphxAm1heG33uaUSQzRh/6LEAuF4gqzudxspme2HCHgkgC9nTXrYP5U1mAultwHdDOuyCHnajqGE+QfH+qE275zcqOhdqG32Mliu24xkxFq8Pohn0CSKDuz5sdgxxznMRiaDrs+HDBfMtyqJE6XlyQ6z6ixqdj5XL9zleR99e77u0ZSJX/yIlVRNZHjr5KurEW0AlLjAwcX7XkI+93W9ym/IIHUTt,iv:rLObgdQJV9jLjAzt6dsVzAgLLBRywVQICOem1fzq5g0=,tag:BsPR/AkmZCwP3td36P/5UA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1vrkd2lkaazv7spv24r3lmxasuhew82yda7klaxt6cenfl7ce2y6qaxe8y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrN1duOVBZRnJNaFhSQ0pj
            TUxkcHBHeEhLOG5GblNpZHU3SHFNODcvZTNZCkpiWm1HeHE4dTQ5eDFOd3JmTDFS
            SHBoVkRYSTZZU2JRTmVjZDBqZ1I5T1UKLS0tIGJtZjdPQW53YldKajNObmNLdWpQ
            TjZGK01XTkdmdEwwTE03UGZmWFBNcm8KIFF5WFOv+lUziy61gJQkkHRHcVxdjrMi
            s6ZjejhYiioK4QK7z4lc3/j/uFWZfPN+4H6Dw7Zx5g7fMcrm4gthgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-25T23:57:07Z"
    mac: ENC[AES256_GCM,data:Dcp9wgKmf3HAwf3xnEosvY/y4Liv6DTZ3szMTFkllk22+f8Sz7a+/9RlahnswMM5OkRFYa2HTbyUxKjG5XMm7f7G2uXd6eyAJf/mY6KPwCZtJcWm/+dFYleSyu5iw3Q03BEjp+vfyhXNQJLmmoi06mpgrznBglvwL5xkIKcX9CA=,iv:xJoDMbQAWS3r9p9vVyKMCdDMf3dRW0XgSbj1gT7Zo/E=,tag:VZokIj8I6a91pyJ8jrQA6w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
