apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9j4h3Tv/KDiyshmevQ3SKHuzP8S48Q1FMlgnfBwrh7JGMyZxXuW0cSozjzE+RDN1nwTqS4BQPiO8Wlh+ERlY0s9s2iTJLOfPaHP5Op9d/yp9Z2nEOac7uDLcPjR1AdEubyWZ3mlLnFQYbawHV/gnNIfvAbh4r4Z2imD6WR0alYpMlqZzdRUJuGdeEYr1f0EgzlCWov2vO/iLDj3PM5krSoZYy52nUUBh6UUwuSpkCmchRC8DVyKMzGh/IBrSJkmmSV952KIpBgEstCvNMgmmLTtxLqqD7GmdB9JBiSpNz1LX0XbwJj6iKbex0IJdGv9Nz6vkL36QPHl7jjTv7YJn3EtDkuODETq2e0zx6Us05nydF5epUgD7v70MJL1vCSsY,iv:lUvOlxHNiWNc8BSyn3A48uzi7hLyxuFx/3XhVY1adnE=,tag:9sVyihroVPp6C+20pZ1Yfw==,type:str]
    identity.pub: ENC[AES256_GCM,data:mbah6J2u0uqJ7JJuh6py3gT61NhV+UdJfTMQf0xxczK8idF/VckA0N9cNhfXcFmXsTx5LpceZIPINMsdqBCFgjAa5U7turRiP8/G6SCkNBfKN9az2DbryoMsvKMOn7dfSHVVHAeBOBxUOdx1ertyVtaIyFoVOLlxHO9H2Rh5uBmf/D+mK1TLM/R25RYwvt0VS00PnM5eDP3xt2709Cu4cEJv2+vJEQ6gJ3bn2r0FIldA36UQyiWKUbdqpUnti8daFigplutlOXEfiw6OEQ==,iv:4sSvd28cPeDbiDOqcNIViwUVCTqIps5p0ZOrPIBnP+A=,tag:hozb9TzWyyJ1qmh+DRg4eQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:JOtvHb3FnwbG30WoJ6duOXeZnlYIzBDx3GKvSKgHn/5ekx3Q3wjM7YBO8VNbzp7pvZYpmjDkUd4+ouCo3ajOp+faGnCtFWx/TkkKsCYVVLrg5XutNixWZ+SsrR+veaAFgQ2ia7GqDQouY8kqgzypZq9VvhI0fLAf39oo1qVOEDzpA12dPyXVdaB/j1A6m7AHrFTN3FkhrQoS7cmxkzGR8SESf5FGoVZVVlg6,iv:fL+IlnYz44M4/xX3ay8jwZo2HNddD8F7c2YXZNZr0ko=,tag:N0LQn6SuwhLJ4Zc25/mx1A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1vrkd2lkaazv7spv24r3lmxasuhew82yda7klaxt6cenfl7ce2y6qaxe8y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TnBUdkJJQ2lzc0dmZlZa
            NVlMbHpQVVZmQUpya215Ylp2cGdvb2NxRXprCjFOV3p4cG5QdDJWUStPc29tR3U0
            cHJmZzdFanFMNHo5WmNiMHVqYTh3elkKLS0tIDQyelJwSXhDK1ZEcFNYdDNEU2Er
            Ykd2eU9Sa2NRdS85M3hCS1dzbjIvU2MKk0s57kX/XuzV6G8yLX992YUi9u+xkFnT
            /bWSBjWD1lByJwUPYoqEbvCG4oF71EMGvUyM5KpuabqBaalP7qXBzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T04:09:53Z"
    mac: ENC[AES256_GCM,data:Oo7J10fFowFUE9CxV1hqQNnJgjuC+xX1E7+oTenMUzLHJSxx0dEolxekPw1M3zd2/QOKL7Bq5lE3DZ2/G050R6z+E3I1fXqhn3lBR9UqdVAwaF4hpfrWDq77qGv/GQfYegBYsZjmw/IKvzEly0rVQrJhCuVaxlGmBPHCnPxAqRs=,iv:iYQLvApZfiYAmULSYLzu3uoWvaYKEh6hoDkLy0Q9wrQ=,tag:xA4/YeZixVyPtZ2Yf48B4A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
